## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "D-Modules" );
LoadPackage( "IO_ForHomalg" );
HOMALG_IO.show_banners := false;
HOMALG_IO.use_common_stream := true;
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "D-Modules", "doc" )[1]![1], "D-Modules.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "D-Modules" );
QUIT;
